#!/usr/bin/env bash
# noshit-f0-documenso — local secret + certificate generation.
#
# Produces the gitignored files the stack needs at boot:
#   .env                     random secrets (db password, auth/crypto keys)
#   data/cert.p12            self-signed local signing certificate
#   data/faketime/faketimerc libfaketime control file for the sidecar clock
#
# Idempotent: keeps existing files unless run with --force.
set -euo pipefail
cd "$(dirname "$0")"
FORCE="${1:-}"

mkdir -p data data/faketime

# --- .env (secrets) ---------------------------------------------------------
if [[ -f .env && "$FORCE" != "--force" ]]; then
  echo "[setup] .env exists — keeping it (pass --force to regenerate)"
else
  echo "[setup] generating .env with fresh random secrets"
  cat > .env <<EOF
# GENERATED by setup.sh on $(date -u +%FT%TZ) — DO NOT COMMIT
POSTGRES_PASSWORD=$(openssl rand -hex 16)
NEXTAUTH_SECRET=$(openssl rand -hex 32)
NEXT_PRIVATE_ENCRYPTION_KEY=$(openssl rand -hex 32)
NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=$(openssl rand -hex 32)
NEXT_PRIVATE_SIGNING_PASSPHRASE=$(openssl rand -hex 12)
EOF
  chmod 600 .env
fi

# shellcheck disable=SC1091
set -a; source .env; set +a

# --- signing certificate ----------------------------------------------------
# Documenso's /api/health cert check only requires a non-empty file at the
# mounted path, but we generate a genuine self-signed p12 anyway so the leg is
# realistic and document-signing would work if exercised.
if [[ -f data/cert.p12 && "$FORCE" != "--force" ]]; then
  echo "[setup] data/cert.p12 exists — keeping it"
else
  echo "[setup] generating self-signed signing certificate -> data/cert.p12"
  openssl req -x509 -newkey rsa:2048 -sha256 -days 3650 -nodes \
    -keyout data/key.pem -out data/cert.pem \
    -subj "/CN=No Shit F0 Documenso/O=noshit-f0" >/dev/null 2>&1
  # -legacy maximizes p12 reader compatibility; fall back if the provider is absent.
  openssl pkcs12 -export -legacy -inkey data/key.pem -in data/cert.pem \
    -out data/cert.p12 -name documenso \
    -passout pass:"${NEXT_PRIVATE_SIGNING_PASSPHRASE}" >/dev/null 2>&1 \
  || openssl pkcs12 -export -inkey data/key.pem -in data/cert.pem \
    -out data/cert.p12 -name documenso \
    -passout pass:"${NEXT_PRIVATE_SIGNING_PASSPHRASE}" >/dev/null 2>&1
  # World-readable so the non-root Documenso container user can read the mount
  # (throwaway self-signed F0 cert; the real secret material is the .env, 600).
  chmod 644 data/cert.p12
fi

# --- faketime control file (rung-2 virtual clock for the scheduler sidecar) --
# Always reset to +0d so each run starts the sidecar at virtual day 0; the demo
# advances it to +31d. (A persisted offset would break the day-30 crossing.)
printf '+0d\n' > data/faketime/faketimerc
echo "[setup] reset data/faketime/faketimerc to +0d (virtual day 0)"

echo "[setup] done."
