#!/usr/bin/env bash
# noshit-f1-woocommerce — local secrets + durable runtime directories.
#
# Runs BEFORE `compose up` (compose interpolation needs .env). Produces:
#   .env                                      random DB + admin passwords (gitignored)
#   /home/user/fixture-runtime/woocommerce/   durable bind-mount roots (db/, html/)
#
# Idempotent: keeps an existing .env unless run with --force. Passwords are
# hex-only (shell/YAML/SQL-safe) and are never echoed by any script in this leg.
set -euo pipefail
cd "$(dirname "$0")"
FORCE="${1:-}"

RUNTIME_DIR="/home/user/fixture-runtime/woocommerce"

# --- .env (secrets) ----------------------------------------------------------
if [[ -f .env && "$FORCE" != "--force" ]]; then
  echo "[setup] .env exists — keeping it (pass --force to regenerate)"
else
  echo "[setup] generating .env with fresh random secrets"
  cat > .env <<EOF
# GENERATED by setup.sh on $(date -u +%FT%TZ) — DO NOT COMMIT
MARIADB_ROOT_PASSWORD=$(openssl rand -hex 16)
WORDPRESS_DB_PASSWORD=$(openssl rand -hex 16)
WP_ADMIN_USER=f1admin
WP_ADMIN_PASSWORD=$(openssl rand -hex 16)
WP_ADMIN_EMAIL=admin@noshit.test
WP_SITE_TITLE=NoShit F1 Storefront
EOF
  chmod 600 .env
fi

# --- durable runtime dirs (bind mounts; NOT named volumes) --------------------
# db/   -> mariadb /var/lib/mysql   (entrypoint chowns to the image's mysql uid)
# html/ -> wordpress /var/www/html  (entrypoint populates WP core on first boot)
#
# html/ starts 0777 so BOTH the root-run wordpress entrypoint AND the uid-33
# (www-data) wpcli container can create top-level files in it (wp-config.php,
# .htaccess-class files). Throwaway fixture-runtime scratch — not repo state.
# The wordpress entrypoint chowns html/ to www-data on first boot, so the
# chmod only applies while we still own the dir (first creation); on re-runs
# the bootstrapped ownership/perms are already correct and are left alone.
mkdir -p "$RUNTIME_DIR/db" "$RUNTIME_DIR/html"
if [[ -O "$RUNTIME_DIR/html" ]]; then
  chmod 0777 "$RUNTIME_DIR/html"
fi
echo "[setup] durable runtime dirs ready under $RUNTIME_DIR (db/, html/)"

echo "[setup] done."
