#!/usr/bin/env bash
# noshit-f1-discourse — LIGHT one-time prep (no heavy pulls; fast, idempotent).
#
# Produces the gitignored .env (non-secret fixture identifiers), the durable
# bind-mount dirs under /home/user/fixture-runtime/discourse, the shared docker
# network the launcher + mailpit both join, renders the launcher container yml
# from the committed template, and stages the provisioning files the container
# reads from /shared. It does NOT pull the base image or bootstrap Discourse —
# that heavy, df-gated step is ./bootstrap.sh. Never prints secrets.
set -euo pipefail
cd "$(dirname "$0")"
FORCE="${1:-}"

RUNTIME_DIR="/home/user/fixture-runtime/discourse"
LAUNCHER_DIR="${RUNTIME_DIR}/discourse_docker"
SHARED="${RUNTIME_DIR}/shared/standalone"
NET="noshit-f1-discourse-net"
ADMIN_EMAIL="admin@noshit.test"      # fixture identifier, NOT a secret
ADMIN_USERNAME="noshit_admin"

echo "== noshit-f1-discourse — setup =="

# --- docker usable? ---------------------------------------------------------
if ! sg docker -c "docker version" >/dev/null 2>&1; then
  echo "FATAL: docker not usable via 'sg docker -c'"; exit 1
fi

# --- durable dirs (bind-mount targets; outside the repo) ---------------------
mkdir -p "${SHARED}/log/var-log"
# build-rw shunt: the build's write-heavy paths bind-mount here, bypassing the
# container overlay layer AND the docker-commit duplicate (see the volumes
# comment in discourse.yml.template). uid 1000 == container discourse user.
mkdir -p "${RUNTIME_DIR}/build-rw"/{app-tmp,public-assets}
echo "[ok] durable shared dir: ${SHARED} (+ build-rw shunt dirs)"

# --- launcher (third-party, outside the repo tree) --------------------------
if [[ ! -x "${LAUNCHER_DIR}/launcher" ]]; then
  echo "[..] cloning discourse_docker launcher (scripts only) ..."
  git clone --depth 1 https://github.com/discourse/discourse_docker.git "${LAUNCHER_DIR}"
fi
LAUNCHER_SHA="$(git -C "${LAUNCHER_DIR}" rev-parse --short HEAD 2>/dev/null || echo unknown)"
echo "[ok] launcher present @ ${LAUNCHER_SHA} (${LAUNCHER_DIR})"

# --- shared bridge network (launcher + mailpit both join it) ----------------
if sg docker -c "docker network inspect ${NET}" >/dev/null 2>&1; then
  echo "[ok] network present: ${NET}"
else
  sg docker -c "docker network create ${NET}" >/dev/null
  echo "[ok] network created: ${NET}"
fi

# --- mailpit image (reuse pinned local image; never a heavy pull) -----------
MAILPIT="axllent/mailpit:v1.30.4@sha256:5a49a77c5bdbe7c5474450b4f46348d09949df3695257729c93a30369382d4f6"
if sg docker -c "docker image inspect '${MAILPIT}'" >/dev/null 2>&1; then
  echo "[ok] mailpit image present (reused, pinned)"
else
  echo "[..] pulling mailpit (pinned, ~34MB) ..."
  sg docker -c "docker pull '${MAILPIT}'" || { echo "FATAL: mailpit pull failed"; exit 1; }
fi

# --- .env (non-secret identifiers; the API key is appended by demo.sh) ------
if [[ -f .env && "$FORCE" != "--force" ]]; then
  echo "[ok] .env exists — keeping it (pass --force to regenerate)"
else
  echo "[..] writing .env (non-secret identifiers)"
  cat > .env <<EOF
# GENERATED by setup.sh on $(date -u +%FT%TZ) — DO NOT COMMIT.
# Non-secret fixture identifiers. The admin API key (DISCOURSE_API_KEY) is
# minted by provision/admin_seed.rb and appended here (0600) by demo.sh.
DISCOURSE_DEVELOPER_EMAILS=${ADMIN_EMAIL}
ADMIN_USERNAME=${ADMIN_USERNAME}
EOF
  chmod 600 .env
  echo "[ok] wrote .env (0600)"
fi
# shellcheck disable=SC1091
set -a; . ./.env; set +a

# --- render launcher container yml from the committed template --------------
mkdir -p "${LAUNCHER_DIR}/containers"
sed "s|@@DEVELOPER_EMAILS@@|${DISCOURSE_DEVELOPER_EMAILS}|g" \
  discourse.yml.template > "${LAUNCHER_DIR}/containers/noshit-f1-discourse.yml"
echo "[ok] rendered containers/noshit-f1-discourse.yml (dev email = ${DISCOURSE_DEVELOPER_EMAILS})"

# --- stage provisioning files the container reads from /shared --------------
cp provision/*.rb "${SHARED}/"
printf '%s\n' "${DISCOURSE_DEVELOPER_EMAILS}" > "${SHARED}/provision_email.txt"
echo "[ok] staged /shared/{admin_seed,sidekiq_drain,clock_note}.rb + provision_email.txt"

echo "== setup complete =="
echo "   next: ./bootstrap.sh   (one-time, df-gated heavy build — 15-25 min)"
echo "   then: ./demo.sh        (repeatable proof: signup round-trip + absence + seed + plugin)"
