#!/usr/bin/env bash
# noshit-f1-listmonk — one-time local prep.
#
# Produces the gitignored .env the stack needs at boot (random DB password +
# random Super Admin password), ensures the durable Postgres data directory
# exists under /home/user/fixture-runtime, and verifies the pinned images are
# present (pulling only listmonk if missing — postgres/mailpit are reused).
#
# Idempotent: keeps an existing .env unless run with --force. Never prints
# secrets.
set -euo pipefail
cd "$(dirname "$0")"
FORCE="${1:-}"

RUNTIME_DIR="/home/user/fixture-runtime/listmonk"
LISTMONK_IMAGE="listmonk/listmonk:v6.2.0@sha256:f535d59e14991337a9f2d570273685378ae86b0d7698c3e00da444e3bc205286"

echo "== noshit-f1-listmonk — setup =="

# --- durable Postgres data directory (bind mount target) --------------------
mkdir -p "${RUNTIME_DIR}/db"
echo "[ok] durable data dir: ${RUNTIME_DIR}/db"

# --- .env (secrets) ---------------------------------------------------------
if [[ -f .env && "$FORCE" != "--force" ]]; then
  echo "[ok] .env exists — keeping it (pass --force to regenerate)"
else
  echo "[..] generating .env with fresh random secrets"
  cat > .env <<EOF
# GENERATED by setup.sh on $(date -u +%FT%TZ) — DO NOT COMMIT
POSTGRES_PASSWORD=$(openssl rand -hex 16)
LISTMONK_ADMIN_USER=admin
LISTMONK_ADMIN_PASSWORD=$(openssl rand -hex 16)
EOF
  chmod 600 .env
  echo "[ok] wrote .env (0600)"
fi

# --- images -----------------------------------------------------------------
if ! sg docker -c "docker version" >/dev/null 2>&1; then
  echo "FATAL: docker not usable via 'sg docker -c'"; exit 1
fi
for img in "postgres:15-alpine" "axllent/mailpit:v1.30.4"; do
  if sg docker -c "docker image inspect '$img'" >/dev/null 2>&1; then
    echo "[ok] image present (reused): $img"
  else
    echo "FATAL: expected local image missing: $img (reuse required, not pulling)"; exit 1
  fi
done
if sg docker -c "docker image inspect '$LISTMONK_IMAGE'" >/dev/null 2>&1; then
  echo "[ok] image present: listmonk (pinned)"
else
  echo "[..] pulling listmonk (pinned) ..."
  sg docker -c "docker pull '$LISTMONK_IMAGE'" || { echo "FATAL: listmonk pull failed"; exit 1; }
fi

echo "== setup complete — run ./demo.sh =="
