#!/usr/bin/env bash
# noshit-f1-plausible — one-time local prep.
#
# Produces the gitignored .env the stack needs at boot (random Postgres password,
# SECRET_KEY_BASE, TOTP_VAULT_KEY), ensures the durable data directories exist
# under /home/user/fixture-runtime/plausible, and verifies the pinned images are
# present (pulling only if missing — mailpit is reused when local).
#
# Secret generation follows Plausible's own quickstart:
#   SECRET_KEY_BASE = openssl rand -base64 48   (>= 64-byte string)
#   TOTP_VAULT_KEY  = openssl rand -base64 32    (32-byte AES key for the TOTP vault)
# POSTGRES_PASSWORD is hex (URL-safe: it is embedded in DATABASE_URL).
#
# Idempotent: keeps an existing .env unless run with --force. Never prints secrets.
set -euo pipefail
cd "$(dirname "$0")"
FORCE="${1:-}"

RUNTIME_DIR="/home/user/fixture-runtime/plausible"
PLAUSIBLE_IMAGE="ghcr.io/plausible/community-edition:v3.2.1@sha256:33e60bfb40f2df5da00f8753b76fad04f67dba3abe6d73eb516e440e3fb62985"
CLICKHOUSE_IMAGE="clickhouse/clickhouse-server:24.12-alpine@sha256:cd450891db46cc6ffe313ca2b0fb7dbfb897a6873ca74a724cbe050a2cf62621"
POSTGRES_IMAGE="postgres:16-alpine@sha256:57c72fd2a128e416c7fcc499958864df5301e940bca0a56f58fddf30ffc07777"
MAILPIT_IMAGE="axllent/mailpit:v1.30.4@sha256:5a49a77c5bdbe7c5474450b4f46348d09949df3695257729c93a30369382d4f6"

echo "== noshit-f1-plausible — setup =="

# --- durable data directories (bind-mount targets) --------------------------
# db/               Postgres data (accounts, sites, settings)
# clickhouse/data   ClickHouse data (the seeded EVENTS live here)
# clickhouse/logs   ClickHouse server logs (low-log config caps growth)
# captures/         optional artifacts (readback JSON snapshots)
# The datastores run as uid 1000 (pinned in compose), so every file written here
# stays host-owned -> the `rm -rf` reset needs no sudo. NB /var/lib/plausible is
# deliberately NOT bind-mounted (see compose.yaml): it holds no durable state and
# the app's uid-999 runtime user cannot write a uid-1000 host dir.
mkdir -p "${RUNTIME_DIR}/db" \
         "${RUNTIME_DIR}/clickhouse/data" \
         "${RUNTIME_DIR}/clickhouse/logs" \
         "${RUNTIME_DIR}/captures"
echo "[ok] durable data dirs under: ${RUNTIME_DIR}"

# --- .env (secrets) ---------------------------------------------------------
if [[ -f .env && "$FORCE" != "--force" ]]; then
  echo "[ok] .env exists — keeping it (pass --force to regenerate)"
else
  echo "[..] generating .env with fresh random secrets"
  cat > .env <<EOF
# GENERATED by setup.sh on $(date -u +%FT%TZ) — DO NOT COMMIT
POSTGRES_PASSWORD=$(openssl rand -hex 16)
SECRET_KEY_BASE=$(openssl rand -base64 48)
TOTP_VAULT_KEY=$(openssl rand -base64 32)
EOF
  chmod 600 .env
  echo "[ok] wrote .env (0600)"
fi

# --- images -----------------------------------------------------------------
if ! sg docker -c "docker version" >/dev/null 2>&1; then
  echo "FATAL: docker not usable via 'sg docker -c'"; exit 1
fi

# mailpit is reused if resident (it is small + shared across legs).
if sg docker -c "docker image inspect '$MAILPIT_IMAGE'" >/dev/null 2>&1; then
  echo "[ok] image present (reused): mailpit"
else
  echo "[..] pulling mailpit (pinned by digest) ..."
  sg docker -c "docker pull '$MAILPIT_IMAGE'" || { echo "FATAL: mailpit pull failed"; exit 1; }
fi

for pair in "postgres:$POSTGRES_IMAGE" "clickhouse:$CLICKHOUSE_IMAGE" "plausible:$PLAUSIBLE_IMAGE"; do
  label="${pair%%:*}"; img="${pair#*:}"
  if sg docker -c "docker image inspect '$img'" >/dev/null 2>&1; then
    echo "[ok] image present: $label (pinned by digest)"
  else
    echo "[..] pulling $label (pinned by digest) ..."
    sg docker -c "docker pull '$img'" || { echo "FATAL: $label pull failed"; exit 1; }
  fi
done

echo "== setup complete — run ./demo.sh =="
