#!/usr/bin/env bash
# noshit-f1-twenty — one-time local prep.
#
# Produces the gitignored .env the stack needs at boot (random Postgres password
# + random ENCRYPTION_KEY), ensures the durable data directories exist under
# /home/user/fixture-runtime, and verifies the pinned images are present
# (pulling only Twenty if missing — postgres/redis/mailpit are reused when local).
#
# Idempotent: keeps an existing .env unless run with --force. Never prints
# secrets.
set -euo pipefail
cd "$(dirname "$0")"
FORCE="${1:-}"

RUNTIME_DIR="/home/user/fixture-runtime/twenty"
TWENTY_IMAGE="twentycrm/twenty:v2.20.0@sha256:1d1c121c56a98fcc365cd8856f605230134958de924619fb1e03af2812c456ae"

echo "== noshit-f1-twenty — setup =="

# --- durable data directories (bind-mount targets) --------------------------
# db/                    Postgres data (the seeded workspace lives here)
# server-local-storage/  Twenty attachments/.local-storage
# captures/              CSV-export artifact (optional nli bonus)
# The Twenty image runs as uid 1000 and Postgres is pinned to uid 1000, so every
# file written here stays host-owned -> the `rm -rf` reset needs no sudo.
mkdir -p "${RUNTIME_DIR}/db" "${RUNTIME_DIR}/server-local-storage" "${RUNTIME_DIR}/captures"
echo "[ok] durable data dirs under: ${RUNTIME_DIR}"

# --- .env (secrets) ---------------------------------------------------------
# POSTGRES_PASSWORD is hex (URL-safe: it is embedded in PG_DATABASE_URL, and
# Twenty's own docs warn against special characters there). ENCRYPTION_KEY is
# base64 32 bytes, per Twenty's documented `openssl rand -base64 32`.
if [[ -f .env && "$FORCE" != "--force" ]]; then
  echo "[ok] .env exists — keeping it (pass --force to regenerate)"
else
  echo "[..] generating .env with fresh random secrets"
  cat > .env <<EOF
# GENERATED by setup.sh on $(date -u +%FT%TZ) — DO NOT COMMIT
POSTGRES_PASSWORD=$(openssl rand -hex 16)
ENCRYPTION_KEY=$(openssl rand -base64 32)
EOF
  chmod 600 .env
  echo "[ok] wrote .env (0600)"
fi

# --- images -----------------------------------------------------------------
if ! sg docker -c "docker version" >/dev/null 2>&1; then
  echo "FATAL: docker not usable via 'sg docker -c'"; exit 1
fi
for img in "postgres:16-alpine" "redis:7-alpine" "axllent/mailpit:v1.30.4"; do
  if sg docker -c "docker image inspect '$img'" >/dev/null 2>&1; then
    echo "[ok] image present (reused): $img"
  else
    echo "[..] pulling $img ..."
    sg docker -c "docker pull '$img'" || { echo "FATAL: $img pull failed"; exit 1; }
  fi
done
if sg docker -c "docker image inspect '$TWENTY_IMAGE'" >/dev/null 2>&1; then
  echo "[ok] image present: twenty (pinned by digest)"
else
  echo "[..] pulling twenty (pinned by digest) ..."
  sg docker -c "docker pull '$TWENTY_IMAGE'" || { echo "FATAL: twenty pull failed"; exit 1; }
fi

echo "== setup complete — run ./demo.sh =="
