#!/usr/bin/env bash
# noshit-f1-formbricks — one-time local prep.
#
# Produces the gitignored .env the stack needs at boot (random Postgres password
# + Formbricks' three required secrets), ensures the durable data directories
# exist under /home/user/fixture-runtime, BUILDS the postgres:15-alpine+pgvector
# image locally (base reused; ~1 MB delta), and verifies the pinned images are
# present (pulling only Formbricks if missing — postgres/mailpit are reused).
#
# Idempotent: keeps an existing .env unless run with --force. Never prints
# secrets.
set -euo pipefail
cd "$(dirname "$0")"
FORCE="${1:-}"

RUNTIME_DIR="/home/user/fixture-runtime/formbricks"
FORMBRICKS_IMAGE="ghcr.io/formbricks/formbricks:v3.16.1@sha256:1cd324d2dc82eb906bf3a03ffc7d679b81d2d0ebdb35173669a68afe84350239"
PGVECTOR_TAG="noshit-f1-formbricks-postgres:15-pgvector"

echo "== noshit-f1-formbricks — setup =="

# --- durable data directories (bind-mount targets) --------------------------
# db/       Postgres data (the seeded survey + >=100 responses + founder user)
# uploads/  Formbricks local file storage (app runs as uid 1001 -> world-writable)
mkdir -p "${RUNTIME_DIR}/db" "${RUNTIME_DIR}/uploads"
chmod 0777 "${RUNTIME_DIR}/uploads"   # app uid (1001) != host uid (1000)
echo "[ok] durable data dirs under: ${RUNTIME_DIR}"

# --- .env (secrets) ---------------------------------------------------------
# POSTGRES_PASSWORD is hex (URL-safe: embedded in DATABASE_URL). Formbricks wants
# three hex-32 secrets: NEXTAUTH_SECRET (session), ENCRYPTION_KEY (2FA + single-
# use survey link ids), CRON_SECRET (protects the in-container cron endpoints).
if [[ -f .env && "$FORCE" != "--force" ]]; then
  echo "[ok] .env exists — keeping it (pass --force to regenerate)"
else
  echo "[..] generating .env with fresh random secrets"
  cat > .env <<EOF
# GENERATED by setup.sh on $(date -u +%FT%TZ) — DO NOT COMMIT
POSTGRES_PASSWORD=$(openssl rand -hex 16)
NEXTAUTH_SECRET=$(openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)
CRON_SECRET=$(openssl rand -hex 32)
EOF
  chmod 600 .env
  echo "[ok] wrote .env (0600)"
fi

# --- images -----------------------------------------------------------------
if ! sg docker -c "docker version" >/dev/null 2>&1; then
  echo "FATAL: docker not usable via 'sg docker -c'"; exit 1
fi

# Reuse resident base images (never pulled here — must already be local).
for img in "postgres:15-alpine" "axllent/mailpit:v1.30.4"; do
  if sg docker -c "docker image inspect '$img'" >/dev/null 2>&1; then
    echo "[ok] image present (reused): $img"
  else
    echo "FATAL: expected local image missing: $img (reuse required, not pulling)"; exit 1
  fi
done

# Formbricks CE (pinned by digest); pull only if missing.
if sg docker -c "docker image inspect '$FORMBRICKS_IMAGE'" >/dev/null 2>&1; then
  echo "[ok] image present: formbricks (pinned by digest)"
else
  echo "[..] pulling formbricks (pinned by digest) ..."
  sg docker -c "docker pull '$FORMBRICKS_IMAGE'" || { echo "FATAL: formbricks pull failed"; exit 1; }
fi

# Build the pgvector-enabled Postgres locally FROM the resident postgres:15-alpine
# (base layers shared; ~1 MB delta). Idempotent: only build if the tag is absent.
if sg docker -c "docker image inspect '$PGVECTOR_TAG'" >/dev/null 2>&1; then
  echo "[ok] image present (built): $PGVECTOR_TAG"
else
  echo "[..] building $PGVECTOR_TAG from postgres:15-alpine + pgvector (base reused) ..."
  sg docker -c "docker build -f postgres-pgvector.Dockerfile -t '$PGVECTOR_TAG' ." \
    || { echo "FATAL: pgvector postgres build failed"; exit 1; }
  echo "[ok] built $PGVECTOR_TAG"
fi

echo "== setup complete — run ./demo.sh =="
